# -*- coding: utf-8 -*-
"""week4_predictive_optimization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EP7CQVkSvYqAL_-yOs5UjLincVX0cB4e
"""

!pip install -q pandas numpy scikit-learn matplotlib

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

np.random.seed(42)

# 1. Simulate logistics data
n = 1200
regions = ["North", "South", "East", "West", "Central"]
modes = ["Road", "Rail", "Air", "Sea"]
warehouses = ["WH-A", "WH-B", "WH-C", "WH-D"]

region = np.random.choice(regions, n)
mode = np.random.choice(modes, n, p=[0.55, 0.15, 0.12, 0.18])
warehouse = np.random.choice(warehouses, n)

volume = np.random.gamma(4.5, 18, n) + 10
distance = np.clip(np.random.lognormal(6.2, 0.48, n), 80, 3000)

mode_delay = {"Road": 0.8, "Rail": 1.8, "Air": -1.2, "Sea": 3.2}
region_delay = {"North": 0.4, "South": 0.0, "East": 0.5, "West": 0.2, "Central": 0.3}

delivery = (
    1.5
    + distance / 550
    + volume / 180
    + np.array([mode_delay[x] for x in mode])
    + np.array([region_delay[x] for x in region])
    + np.random.normal(0, 0.7, n)
)
delivery = np.clip(delivery, 1, None)

cost_rate = {"Road": 9.5, "Rail": 6.5, "Air": 22.0, "Sea": 4.5}
cost = (
    volume * np.array([cost_rate[x] for x in mode])
    + distance * 0.08
    + np.random.normal(0, 80, n)
)
cost = np.clip(cost, 80, None)

data = pd.DataFrame({
    "shipment_id": [f"SHP-{i:04d}" for i in range(1, n + 1)],
    "region": region,
    "transport_mode": mode,
    "warehouse": warehouse,
    "shipment_volume_kg": np.round(volume, 2),
    "distance_km": np.round(distance, 2),
    "transport_cost": np.round(cost, 2),
    "delivery_time_days": np.round(delivery, 2)
})

# 2. Simulate missing values and clean them
idx = np.random.choice(n, 20, replace=False)
data.loc[idx[:10], "transport_cost"] = np.nan
data.loc[idx[10:], "shipment_volume_kg"] = np.nan

data["transport_cost"] = data["transport_cost"].fillna(
    data["transport_cost"].median()
)
data["shipment_volume_kg"] = data["shipment_volume_kg"].fillna(
    data["shipment_volume_kg"].median()
)

# 3. Prepare features and target
X = data.drop(columns=["shipment_id", "delivery_time_days"])
y = data["delivery_time_days"]

categorical = ["region", "transport_mode", "warehouse"]
numerical = ["shipment_volume_kg", "distance_km", "transport_cost"]

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
    ("num", "passthrough", numerical)
])

# 4. Train and compare models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(
        n_estimators=250,
        max_depth=12,
        random_state=42
    )
}

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

results = []

for name, model in models.items():
    pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model)
    ])

    pipeline.fit(X_train, y_train)
    predictions = pipeline.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    r2 = r2_score(y_test, predictions)

    results.append([name, mae, rmse, r2])

results_df = pd.DataFrame(
    results,
    columns=["Model", "MAE", "RMSE", "R2"]
).sort_values("RMSE")

print("\nModel Performance:")
print(results_df)

# 5. Select best model
best_name = results_df.iloc[0]["Model"]

best_model = models[best_name]

best_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", best_model)
])

best_pipeline.fit(X_train, y_train)

predictions = best_pipeline.predict(X_test)

print("\nBest Model:", best_name)
print("MAE:", mean_absolute_error(y_test, predictions))
print("RMSE:", np.sqrt(mean_squared_error(y_test, predictions)))
print("R2:", r2_score(y_test, predictions))

# 6. Cross-validation
cv_scores = cross_val_score(
    best_pipeline,
    X,
    y,
    cv=5,
    scoring="neg_mean_absolute_error"
)

print(
    "\n5-Fold Cross-Validation MAE:",
    -cv_scores.mean()
)

# 7. Optimization scenario
# Compare hypothetical transport options using predicted delivery time
scenario = pd.DataFrame({
    "region": ["North", "South", "East", "West", "Central"] * 4,
    "transport_mode": np.repeat(modes, 5),
    "warehouse": np.random.choice(
        warehouses, 20
    ),
    "shipment_volume_kg": np.random.choice(
        [40, 70, 100, 140], 20
    ),
    "distance_km": np.random.choice(
        [300, 600, 900, 1400, 2000], 20
    ),
    "transport_cost": np.random.choice(
        [450, 700, 1000, 1500, 2200], 20
    )
})

scenario["predicted_delivery_days"] = (
    best_pipeline.predict(scenario)
)

# Weighted objective:
# 50% cost + 50% delivery time
scenario["cost_norm"] = (
    (scenario["transport_cost"] - scenario["transport_cost"].min())
    / (
        scenario["transport_cost"].max()
        - scenario["transport_cost"].min()
    )
)

scenario["time_norm"] = (
    (scenario["predicted_delivery_days"]
     - scenario["predicted_delivery_days"].min())
    / (
        scenario["predicted_delivery_days"].max()
        - scenario["predicted_delivery_days"].min()
    )
)

scenario["optimization_score"] = (
    0.5 * scenario["cost_norm"]
    + 0.5 * scenario["time_norm"]
)

recommendations = scenario.sort_values(
    "optimization_score"
).head(10)

print("\nTop Optimization Recommendations:")
print(recommendations)

recommendations.to_csv(
    "optimized_transport_recommendations.csv",
    index=False
)

data.to_csv(
    "week4_logistics_dataset.csv",
    index=False
)

results_df.to_csv(
    "model_comparison.csv",
    index=False
)

print("\nWeek 4 project completed successfully.")