# -*- coding: utf-8 -*-
"""week2_preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6Dax9iv_Vjl1eA_eQ4c94kAgevDukvU
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler


customers = pd.read_csv(
    "olist_customers_dataset.csv"
)

geolocation = pd.read_csv(
    "olist_geolocation_dataset.csv"
)


print("WEEK 2 DATA QUALITY ASSESSMENT")


print("\nCustomer Dataset Shape:")
print(customers.shape)


print("\nGeolocation Dataset Shape:")
print(geolocation.shape)


print("\nCustomer Dataset Preview:")
print(customers.head())


print("\nCustomer Dataset Information:")
customers.info()


print("\nCustomer Dataset Data Types:")
print(customers.dtypes)


print("\nMissing Values in Customer Dataset:")
print(customers.isnull().sum())


print("\nMissing Values in Geolocation Dataset:")
print(geolocation.isnull().sum())


print("\nDuplicate Customer Rows:")
print(customers.duplicated().sum())


print("\nDuplicate Geolocation Rows:")
print(geolocation.duplicated().sum())


print("\nTotal Customer Records:")
print(len(customers))


print("\nUnique Customer IDs:")
print(customers["customer_id"].nunique())


print("\nDuplicate customer_id values:")
print(
    customers["customer_id"].duplicated().sum()
)


print("\nUnique Customers:")
print(
    customers["customer_unique_id"].nunique()
)


print("\nRepeated customer_unique_id values:")
print(
    customers["customer_unique_id"].duplicated().sum()
)


print("\nNumber of Customer States:")
print(
    customers["customer_state"].nunique()
)


print("\nNumber of Customer Cities:")
print(
    customers["customer_city"].nunique()
)


print("\nCustomer State Distribution:")
print(
    customers["customer_state"]
    .value_counts()
    .head(10)
)


print("\nCustomer City Distribution:")
print(
    customers["customer_city"]
    .value_counts()
    .head(10)
)


print("\nZIP Code Statistics:")
print(
    customers[
        "customer_zip_code_prefix"
    ].describe()
)


print("\nDATA CLEANING AND PREPROCESSING")


original_rows = len(customers)


customers = customers.drop_duplicates()


print("\nDuplicate rows removed:")
print(
    original_rows - len(customers)
)


categorical_columns = [
    "customer_city",
    "customer_state"
]


for column in categorical_columns:

    customers[column] = (
        customers[column]
        .fillna("Unknown")
    )


customers["customer_zip_code_prefix"] = (
    customers["customer_zip_code_prefix"]
    .fillna(
        customers[
            "customer_zip_code_prefix"
        ].median()
    )
)


print("\nMissing values after handling:")
print(
    customers.isnull().sum()
)


customers["customer_city"] = (
    customers["customer_city"]
    .astype(str)
    .str.strip()
    .str.lower()
)


customers["customer_state"] = (
    customers["customer_state"]
    .astype(str)
    .str.strip()
    .str.upper()
)


customers["customer_zip_code_prefix"] = pd.to_numeric(
    customers["customer_zip_code_prefix"],
    errors="coerce"
)


invalid_zip = (
    (customers["customer_zip_code_prefix"] < 0)
    |
    (customers["customer_zip_code_prefix"] > 99999)
)


print("\nInvalid ZIP code records:")
print(
    invalid_zip.sum()
)


customers = customers[
    ~invalid_zip
].copy()


customers["customer_zip_code_prefix"] = (
    customers["customer_zip_code_prefix"]
    .astype(int)
)


customers["zip_prefix_2digit"] = (
    customers[
        "customer_zip_code_prefix"
    ]
    .astype(str)
    .str.zfill(5)
    .str[:2]
)


def assign_region(state):

    north = [
        "AC", "AP", "AM",
        "PA", "RO", "RR", "TO"
    ]

    northeast = [
        "AL", "BA", "CE",
        "MA", "PB", "PE",
        "PI", "RN", "SE"
    ]

    central_west = [
        "DF", "GO", "MT", "MS"
    ]

    southeast = [
        "ES", "MG", "RJ", "SP"
    ]

    south = [
        "PR", "RS", "SC"
    ]

    if state in north:
        return "North"

    elif state in northeast:
        return "Northeast"

    elif state in central_west:
        return "Central-West"

    elif state in southeast:
        return "Southeast"

    elif state in south:
        return "South"

    return "Unknown"


customers["customer_region"] = (
    customers["customer_state"]
    .apply(assign_region)
)


print("\nCustomer distribution by region:")

print(
    customers["customer_region"]
    .value_counts()
)


state_encoded = pd.get_dummies(
    customers["customer_state"],
    prefix="state",
    dtype=int
)


customers = pd.concat(
    [
        customers,
        state_encoded
    ],
    axis=1
)


scaler = StandardScaler()


customers["zip_scaled"] = (
    scaler.fit_transform(
        customers[
            ["customer_zip_code_prefix"]
        ]
    )
)


print("\nSTANDARDIZED ZIP CODE STATISTICS")

print(
    customers["zip_scaled"].describe()
)


print("\nGEOLOCATION PROCESSING")


geo_coordinates = (
    geolocation
    .groupby(
        "geolocation_zip_code_prefix"
    )
    .agg(
        latitude=(
            "geolocation_lat",
            "mean"
        ),
        longitude=(
            "geolocation_lng",
            "mean"
        )
    )
    .reset_index()
)


customers_for_geo = customers.rename(
    columns={
        "customer_zip_code_prefix":
        "geolocation_zip_code_prefix"
    }
)


customers_clean = customers_for_geo.merge(
    geo_coordinates,
    on="geolocation_zip_code_prefix",
    how="left"
)


print("\nFinal cleaned dataset shape:")
print(
    customers_clean.shape
)


print("\nMissing values after preprocessing:")

print(
    customers_clean.isnull().sum()
)


print("\nFinal dataset preview:")

print(
    customers_clean.head()
)


customers_clean.to_csv(
    "cleaned_customer_data.csv",
    index=False
)


print("\nCleaned dataset saved successfully.")

print(
    "File: cleaned_customer_data.csv"
)


print("\nWEEK 2 PREPROCESSING COMPLETED SUCCESSFULLY")