# -*- coding: utf-8 -*-
"""week3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqmyL5uTESZ_JU_XWHOofMY4uo9vQ1KM
"""

import pandas as pd
import numpy as np

np.random.seed(42)

n = 1000

regions = [
    "North",
    "South",
    "East",
    "West",
    "Central"
]

transport_modes = [
    "Road",
    "Rail",
    "Air",
    "Sea"
]

warehouses = [
    "WH-A",
    "WH-B",
    "WH-C",
    "WH-D"
]

region = np.random.choice(
    regions,
    n
)

transport_mode = np.random.choice(
    transport_modes,
    n,
    p=[0.55, 0.15, 0.12, 0.18]
)

warehouse = np.random.choice(
    warehouses,
    n
)

shipment_volume = (
    np.random.gamma(
        shape=4.5,
        scale=18,
        size=n
    ) + 10
)

base_delivery_days = {
    "Road": 4.8,
    "Rail": 6.5,
    "Air": 2.0,
    "Sea": 9.0
}

delivery_time = np.array([
    base_delivery_days[mode]
    for mode in transport_mode
])

delivery_time = (
    delivery_time
    + shipment_volume * 0.018
    + np.random.normal(0, 1.15, n)
)

delivery_time = np.clip(
    delivery_time,
    1,
    None
)

cost_per_unit = {
    "Road": 9.5,
    "Rail": 6.5,
    "Air": 22.0,
    "Sea": 4.5
}

transport_cost = np.array([
    cost_per_unit[mode]
    for mode in transport_mode
])

transport_cost = (
    transport_cost
    * shipment_volume
)

transport_cost = (
    transport_cost
    + delivery_time * 18
    + np.random.normal(0, 90, n)
)

transport_cost = np.clip(
    transport_cost,
    80,
    None
)

distance = np.random.lognormal(
    mean=6.2,
    sigma=0.48,
    size=n
)

distance = np.clip(
    distance,
    80,
    3000
)

fuel_cost = (
    distance * 0.055
    + np.random.normal(0, 15, n)
)

fuel_cost = np.clip(
    fuel_cost,
    10,
    None
)

on_time_probability = (
    0.93
    - 0.035 * (delivery_time > 7)
    - 0.025 * (shipment_volume > 120)
    + np.random.normal(0, 0.018, n)
)

on_time_probability = np.clip(
    on_time_probability,
    0.55,
    0.99
)

on_time = np.random.binomial(
    1,
    on_time_probability
)

data = pd.DataFrame({
    "shipment_id": [
        f"SHP-{i:04d}"
        for i in range(1, n + 1)
    ],
    "region": region,
    "transport_mode": transport_mode,
    "warehouse": warehouse,
    "shipment_volume_kg": np.round(
        shipment_volume,
        2
    ),
    "delivery_time_days": np.round(
        delivery_time,
        2
    ),
    "distance_km": np.round(
        distance,
        2
    ),
    "transport_cost": np.round(
        transport_cost,
        2
    ),
    "fuel_cost": np.round(
        fuel_cost,
        2
    ),
    "on_time_delivery": on_time
})

print(data.head())

print("\nDataset Shape:")
print(data.shape)

print("\nDataset Information:")
print(data.info())

data.to_csv(
    "logistics_simulated_data.csv",
    index=False
)

print(
    "Dataset created successfully!"
)

print(data.describe())

print(
    data.groupby("transport_mode")[
        "transport_cost"
    ].mean()
)

import plotly.express as px

fig = px.scatter(
    data,
    x="shipment_volume_kg",
    y="delivery_time_days",
    color="transport_mode",
    hover_data=[
        "region",
        "warehouse",
        "transport_cost"
    ],
    title="Shipment Volume vs Delivery Time"
)

fig.show()